## Data Encryption and Decryption
* Data Encryption
  - Encryption is a security method in which information is encoded in such a way that only authorized user can read it.It uses encryption algorithm to generate ciphertext that can only be read if decrypted.
* Data Decryption
  - decryption is the process of talking encoded or encrypted text and converting it back into text that you or the computer can read and unerstand
* Types
  -Symmetric (private key): it uses a single key that will be shared among the people who need to receive the message.
* Asymmetric (public  key):
  -Asymmetrical encryption uses a pair of public key and a private key to encrypt and descrypt mesages.
* Write a function to generate key for encryption  

In [2]:
# function to generate key for encryption.
keypath='DataFiles/key.txt'
def generatekey(keypath):
    with open(keypath,'w') as f:
        for i in range(10):
            if i<6:
                f.write(str(i)+' '+str(i+4)+'\n')
            else:
                f.write(str(i)+' '+str(i-6)+'\n')
    return
generatekey(keypath)
                

In [2]:
# Function to decrypt a DataFile
keyfile='DataFiles/key.txt'
def dictionaryKeyFile(keyfile):
    key={}
    with open(keyfile,'r') as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
    return key
def encryptMarksData(datafile,keyfile):
    #construct a dictionary for key data
    key=dictionaryKeyFile(keyfile)
    with open(datafile,'r') as f:
        filedata=f.read().split('\n')
    with open('DataFiles/encryptedMarks.txt','w') as f:
        for mark in filedata:
            line=''
            for n in mark:
                line+=key[n]
            f.write(line+'\n')
    return
datafile='DataFiles/marks.txt'
encryptMarksData(datafile,keyfile)

In [3]:
#Function to decrypt the encrypted file
def decryptMarksData(encryptedfile,keyfile):
    key=dictionaryKeyFile(keyfile)
    newkey={}
    for key,value in key.items():
        newkey[value]=key
    with open(encryptedfile,'r') as f:
        encrypteddata=f.read().split('\n')
    with open('DataFiles/decryptedMarks.txt','w') as f:
        for encryptedmark in encrypteddata:
            line=''
            for n in encryptedmark:
                line+=newkey[n]
                f.write(line+'\n')
    return
encryptedfile='DataFiles/encryptedMarks.txt'
import timeit
st=timeit.default_timer()
decryptMarksData(encryptedfile,keyfile)
print(timeit.default_timer()-st)

0.05012728299999836



### Python Libraries For Data Science
* Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing, processing and analysing the data. It involves many different disciplines like mathematical and statistical modelling, extracting data from it source and applying data visualization techniques. There are nearly 20 python libraries for Data Science. Top five python libraries are
* TensorFlow
* NumPy
* SciPy
* Pandas
* Matplotlib In those libraries, Numpy and Pandas are the first choice to the data scientists who are aware of the technologies.
* NumPy: (Numerical Python)
* Numpy is Base N-Dimensional Array Package, is a python library and a fundamental package for scientific computing in Python. It is used to create multidimensional arrays for fast operations. Use the following import conversion. \Ex: >>import numpy as np
* NumPy Arrays
* NumPy have a fixed size of arrays used to store a collection of elements, unlike python lists. There are three types of arrays called 1D, 2D and 3D arrays.
* Creating 1D and 2D arrays using numPy.

In [7]:
import numpy as np
array_1d=np.array([2,4,5,6,7,9])
print(array_1d)
print(type(array_1d))

[2 4 5 6 7 9]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
array_2d=np.array([[2,3,4],[5,8,7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


* program to print the given list into an array

In [9]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
print(a)

['1' '2' '3' 'z']


In [10]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
a

array(['1', '2', '3', 'z'], dtype='<U11')

* for example, the following code print 1d array between 1 to 15

In [11]:
import numpy as np
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
import numpy as np
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

* For Example,the following code print 1000 in a 1D array

In [16]:
import numpy as np
a2=np.arange(10000)
a2

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [17]:
a2=np.arange(10000).reshape(100,100)
a2

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

### Inspect the structure and Content of array using “ndarrays”
* The most basic object in NumPy is the “ndarray” object or simply an “array”.
* The ndarray has important attributes. They are
* ndarray.ndim: No of dimensions of array referred as “rank”.
* ndarray.shape: Returns the length of the array in tuple.
* ndarray.size: Returns the size of an array.
* ndarray.dtype: We can create or specify “dtype” using standard Python types. NumPy provides types like numpy.int32, numpy.int16, and numpy.float64
* ndarray.itemsize: Returns the size in bytes of each element in an array

Create a2D Array and inspect size,shape,dimesnsions and dtype of the array.

In [18]:
import numpy as np
array1=np.random.randint(0,2,size=(3,3))
array1[2][2]
print('shape:',array1.shape)
print('size:',array1.size)
print('Dtype:',array1.dtype)
print('Itemsize:',array1.itemsize)
print('Data:',array1.data)
array1

shape: (3, 3)
size: 9
Dtype: int32
Itemsize: 4
Data: <memory at 0x0000025569289990>


array([[1, 1, 1],
       [1, 0, 0],
       [1, 0, 1]])

In [19]:
array1=[[1,2,3],[5,6,7]]
a1=np.array(array1)
a1

array([[1, 2, 3],
       [5, 6, 7]])

In [22]:
import numpy as np
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

* Reverse the array using slicing

In [23]:
arr[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

* Create an array of 1's.Take a list & convert it into a 3D array and add 1 to each element in an array

In [24]:
import numpy as np
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
b=[[1,2,3],[10,20,30],[11,22,33]]
c=np.array(b)
c

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 22, 33]])

In [26]:
d=c+1
c

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 22, 33]])

* We can perform arithmetic operators in NumPy like addition,subtraction etc.,and of course log,sin,cos,etc

In [27]:
a=np.arange(1,7).reshape(2,3)
b=np.arange(5,11).reshape(2,3)
print(a,)
print(b,'\n')
print(a+b)
print(a/b)

[[1 2 3]
 [4 5 6]]
[[ 5  6  7]
 [ 8  9 10]] 

[[ 6  8 10]
 [12 14 16]]
[[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]
